use crate::layout::PAGE_SIZE;

pub const HEADER_SIGNATURE_SIZE: u64 = 0x200;
pub const XVD_HEADER_SIZE: u64 = 0x2E00;
pub const XVD_HEADER_INCL_SIGNATURE_SIZE: u64 = HEADER_SIGNATURE_SIZE + XVD_HEADER_SIZE;

pub const INVALID_SECTOR: u32 = 0xFFFFFFFF;

pub const HASH_ENTRY_LENGTH: usize = 0x18;
pub const HASH_ENTRY_LENGTH_ENCRYPTED: usize = 0x14;

pub const HASH_ENTRIES_IN_PAGE: usize = PAGE_SIZE / HASH_ENTRY_LENGTH;

pub const DATA_BLOCKS_IN_LEVEL0_HASHTREE: usize = HASH_ENTRIES_IN_PAGE;
pub const DATA_BLOCKS_IN_LEVEL1_HASHTREE: usize =
    HASH_ENTRIES_IN_PAGE * DATA_BLOCKS_IN_LEVEL0_HASHTREE;
pub const DATA_BLOCKS_IN_LEVEL2_HASHTREE: usize =
    HASH_ENTRIES_IN_PAGE * DATA_BLOCKS_IN_LEVEL1_HASHTREE;
pub const DATA_BLOCKS_IN_LEVEL3_HASHTREE: usize =
    HASH_ENTRIES_IN_PAGE * DATA_BLOCKS_IN_LEVEL2_HASHTREE;
