[package]
name = "msixvc"
version = "0.1.0"
edition = "2024"

[dependencies]
msixvc-common = { path = "../msixvc-common" }

tokio = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
aes = "0.9.2"
bitflags = "2.13.1"
bytes = "1.12.1"
futures-util = "0.3.34"
gpt = "4.1.0"
ntfs = "0.4.0"
num_enum = "0.7.6"
tokio-util = { version = "0.7.19", features = ["io-util"] }
typenum = { version = "1.20.1", features = ["const-generics"] }
zerocopy = { version = "0.8.56", features = ["derive"] }
